import { readdirSync, statSync, readFileSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function getFiles(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function getDirectories(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isDirectory();
  });
}

function getArtifactOfContract(contractName) {
  const artifactPath = join(__dirname, "..", `out/${contractName}.sol`, `${contractName}.json`);

  if (!existsSync(artifactPath)) return null;

  return JSON.parse(readFileSync(artifactPath, "utf8"));
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact?.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(({ baseName }) => baseName.name);
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function readJsonFile(filePath) {
  try {
    return JSON.parse(readFileSync(filePath, "utf8"));
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}: ${error.message}`);
    return null;
  }
}

function parseBlockNumber(blockNumber) {
  if (!blockNumber) {
    return undefined;
  }

  return Number(BigInt(blockNumber));
}

/** Deployment block of every contract created by a forge broadcast on `chainId`, keyed by lowercase address. */
function getBroadcastDeployments(chainId) {
  const broadcastPath = join(__dirname, "..", "broadcast");
  const deploymentsByAddress = {};

  for (const scriptDir of getDirectories(broadcastPath)) {
    const chainBroadcastPath = join(broadcastPath, scriptDir, chainId);

    for (const broadcastFile of getFiles(chainBroadcastPath).filter(
      file => file.startsWith("run-") && file.endsWith(".json"),
    )) {
      const broadcast = readJsonFile(join(chainBroadcastPath, broadcastFile));

      if (!broadcast?.transactions?.length || !broadcast?.receipts?.length) {
        continue;
      }

      for (const transaction of broadcast.transactions) {
        if (transaction.transactionType !== "CREATE" || !transaction.contractAddress) {
          continue;
        }

        const receipt = broadcast.receipts.find(({ transactionHash }) => transactionHash === transaction.hash);
        const deployedOnBlock = parseBlockNumber(receipt?.blockNumber);

        if (deployedOnBlock === undefined) {
          continue;
        }

        deploymentsByAddress[transaction.contractAddress.toLowerCase()] = { deployedOnBlock };
      }
    }
  }

  return deploymentsByAddress;
}

/**
 * deployments/<chainId>.json files are the source of truth: every chain found there is merged into the output, so a
 * local deploy never drops the committed testnet entry.
 */
function processDeploymentExports(deploymentsPath) {
  const allContracts = {};
  const deploymentFiles = getFiles(deploymentsPath).filter(file => file.endsWith(".json"));

  deploymentFiles.forEach(deploymentFile => {
    const chainId = deploymentFile.slice(0, -5);
    const broadcastDeployments = getBroadcastDeployments(chainId);
    const deploymentObject = readJsonFile(join(deploymentsPath, deploymentFile));

    if (!deploymentObject) return;

    Object.entries(deploymentObject).forEach(([address, contractName]) => {
      if (address === "networkName") return;

      if (typeof contractName !== "string") {
        console.warn(`Warning: Skipping deployment entry ${chainId}.${address}; contract name must be a string.`);
        return;
      }

      const artifact = getArtifactOfContract(contractName);

      if (!artifact) {
        console.warn(
          `Warning: Missing artifact for ${contractName}; skipping ${address} on chain ${chainId}. Run \`forge build\` first.`,
        );
        return;
      }

      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
        ...broadcastDeployments[address.toLowerCase()],
      };
    });
  });

  return allContracts;
}

async function main() {
  const allGeneratedContracts = processDeploymentExports(join(__dirname, "..", "deployments"));

  // Resolve nextjs contracts dir from this package (packages/foundry/scripts-js -> packages/nextjs/contracts)
  const NEXTJS_TARGET_DIR = join(__dirname, "..", "..", "nextjs", "contracts");

  if (!existsSync(NEXTJS_TARGET_DIR)) {
    mkdirSync(NEXTJS_TARGET_DIR, { recursive: true });
  }

  const fileContent = Object.entries(allGeneratedContracts).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  const fileTemplate = importPath => `
    ${generatedContractComment}
    import { GenericContractsDeclaration } from "${importPath}";

    const deployedContracts = {${fileContent}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;

  // Prettier 3's format() is async; without the await the file would contain "[object Promise]".
  const formatted = await format(fileTemplate("~~/utils/scaffold-hbar/contract"), { parser: "typescript" });
  const targetFile = join(NEXTJS_TARGET_DIR, "deployedContracts.ts");
  writeFileSync(targetFile, formatted);

  console.log(`Updated TypeScript contract definition file on ${targetFile}`);
}

main().catch(error => {
  console.error("Error:", error);
  process.exitCode = 1;
});
